#!/bin/bash

# Script untuk preview reset jawaban UPP TANPA menghapus data
# Hanya untuk demonstrasi dan validasi

echo "======================================"
echo "🔍 PREVIEW: Reset UPP Answers Command"
echo "======================================"
echo ""
echo "✅ Command sudah dibuat di:"
echo "   app/Console/Commands/ResetUppAnswersCommand.php"
echo ""
echo "📖 Dokumentasi lengkap di:"
echo "   docs/reset-upp-answers.md"
echo ""
echo "======================================"
echo "USAGE:"
echo "======================================"
echo ""
echo "1️⃣  Reset satu UPP tertentu:"
echo "   php artisan upp:reset-answers 1"
echo ""
echo "2️⃣  Reset SEMUA UPP:"
echo "   php artisan upp:reset-answers --all"
echo ""
echo "======================================"
echo "CURRENT DATA STATUS:"
echo "======================================"
echo ""

cd "$(dirname "$0")" || exit
php tmp_check_data.php

echo ""
echo "======================================"
echo "⚠️  IMPORTANT NOTES:"
echo "======================================"
echo ""
echo "✓ HANYA menghapus jawaban dari UPP (user input)"
echo "✓ Data master AMAN (UPP, Aspek, Indikator, Pertanyaan, dll)"
echo "✓ Menggunakan database transaction (safe - bisa rollback)"
echo "✓ Hard delete (permanent) - tidak bisa di-undo!"
echo "✓ Command akan meminta konfirmasi sebelum delete"
echo ""
echo "======================================"
echo "DATA YANG AKAN DIHAPUS:"
echo "======================================"
echo ""
echo "F01 - Pengisian Indikator (dari UPP):"
echo "  • f01_pengisian       (jawaban pengisian)"
echo "  • f01_jawaban         (jawaban per pertanyaan)"
echo "  • f01_indikator_nilai (nilai indikator)"
echo "  • f01_indikator_bukti (file bukti)"
echo "  • f01_bukti_dukung    (URL bukti)"
echo "  • f01_aspek_pengisian (status pengerjaan aspek)"
echo ""
echo "F02 - Validasi (dari validator):"
echo "  • f02_validasi            (record validasi)"
echo "  • f02_indikator_validasi  (nilai validasi)"
echo "  • f02_catatan_indikator   (komentar validator)"
echo ""
echo "F03 - Survey Kinerja (dari responden):"
echo "  • f03_pengisian           (submission survey)"
echo "  • f03_jawaban             (jawaban survey)"
echo "  • f03_response_demographic (data demografis)"
echo ""
echo "======================================"
echo "DATA YANG AMAN (TIDAK DIHAPUS):"
echo "======================================"
echo ""
echo "✓ upps                - Data UPP"
echo "✓ aspek               - Data Aspek"
echo "✓ indikator           - Data Indikator"
echo "✓ pertanyaan          - Data Pertanyaan"
echo "✓ periode             - Data Periode"
echo "✓ f02_skor            - Template F02 Scoring"
echo "✓ f03_aspek           - Template F03 Aspek"
echo "✓ f03_indikator       - Template F03 Indikator"
echo "✓ f03_token           - Token F03"
echo "✓ users               - User data"
echo "✓ Semua data lainnya  - TETAP AMAN"
echo ""
echo "======================================"
echo "SIAP UNTUK RESET JAWABAN UPP"
echo "======================================"
echo ""
